name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'ridingintraffic' }}
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:ridingintraffic-wiki/ridingintraffic-wiki.github.io.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.RIDINGINTRAFFIC_WIKI_SSH_PRIVATE_KEY }}
